# Generated by Django 5.2.8 on 2025-12-02 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "national_code",
                    models.CharField(max_length=10, unique=True, verbose_name="کد ملی"),
                ),
                (
                    "service_code",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="کد خدمات"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=11, unique=True, verbose_name="شماره موبایل"
                    ),
                ),
                ("first_name", models.CharField(max_length=50, verbose_name="نام")),
                (
                    "last_name",
                    models.CharField(max_length=50, verbose_name="نام خانوادگی"),
                ),
                (
                    "father_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="نام پدر"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="شهر"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "ادمین"),
                            ("teacher", "معلم"),
                            ("student", "دانش\u200cآموز"),
                        ],
                        default="student",
                        max_length=20,
                        verbose_name="نقش",
                    ),
                ),
                (
                    "phone_verified",
                    models.BooleanField(default=False, verbose_name="موبایل تأیید شده"),
                ),
                (
                    "phone_verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ تأیید موبایل"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                ("is_staff", models.BooleanField(default=False, verbose_name="کارمند")),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "کاربر",
                "verbose_name_plural": "کاربران",
            },
        ),
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=11, verbose_name="شماره موبایل"),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="آی\u200cپی")),
                (
                    "attempt_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان تلاش"),
                ),
                ("successful", models.BooleanField(default=False, verbose_name="موفق")),
            ],
            options={
                "verbose_name": "تلاش ورود",
                "verbose_name_plural": "تلاش\u200cهای ورود",
                "indexes": [
                    models.Index(
                        fields=["phone_number", "attempt_time"],
                        name="accounts_lo_phone_n_0215cb_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "attempt_time"],
                        name="accounts_lo_ip_addr_34593a_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("refresh_token", models.TextField(verbose_name="توکن بازیابی")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="آی\u200cپی"
                    ),
                ),
                (
                    "device",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="دستگاه"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "نشست کاربر",
                "verbose_name_plural": "نشست\u200cهای کاربران",
            },
        ),
        migrations.CreateModel(
            name="PasswordResetOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=11, verbose_name="شماره موبایل"),
                ),
                ("otp_code", models.CharField(max_length=6, verbose_name="کد OTP")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="تاریخ انقضا")),
                (
                    "is_used",
                    models.BooleanField(default=False, verbose_name="استفاده شده"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "کد بازیابی رمز",
                "verbose_name_plural": "کدهای بازیابی رمز",
                "indexes": [
                    models.Index(
                        fields=["phone_number", "otp_code"],
                        name="accounts_pa_phone_n_d47356_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="accounts_pa_expires_d8be21_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SecurityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("LOGIN_SUCCESS", "ورود موفق"),
                            ("LOGIN_FAILED", "ورود ناموفق"),
                            ("PASSWORD_CHANGED", "تغییر رمز عبور"),
                            ("PHONE_VERIFIED", "تأیید موبایل"),
                            ("ROLE_CHANGED", "تغییر نقش"),
                            ("SESSION_REVOKED", "ابطال نشست"),
                            ("USER_CREATED", "ایجاد کاربر"),
                            ("USER_UPDATED", "ویرایش کاربر"),
                            ("USER_DELETED", "حذف کاربر"),
                            ("ADMIN_ACTION", "عملیات ادمین"),
                        ],
                        max_length=50,
                        verbose_name="عملیات",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="آی\u200cپی"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, null=True, verbose_name="User Agent"),
                ),
                ("details", models.JSONField(default=dict, verbose_name="جزئیات")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "لاگ امنیتی",
                "verbose_name_plural": "لاگ\u200cهای امنیتی",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="accounts_se_user_id_2e90a3_idx",
                    ),
                    models.Index(
                        fields=["action", "created_at"],
                        name="accounts_se_action_505bcb_idx",
                    ),
                ],
            },
        ),
    ]
