# Generated by Django 5.2.8 on 2025-12-02 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersession",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 12, 2, 12, 47, 33, 911997, tzinfo=datetime.timezone.utc
                ),
                verbose_name="تاریخ انقضا",
            ),
            preserve_default=False,
        ),
    ]
